//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OToChoThue.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DonThueXe
    {
        [DisplayName("ID Đơn thuê xe")]
        public int DonThueID { get; set; }
        [DisplayName("Tên khách hàng")]
        public string KhachHangID { get; set; }
        [DisplayName("Tên xe")]
        public string XeID { get; set; }
        [DisplayName("Ngày thuê")]
        public Nullable<System.DateTime> NgayThue { get; set; }
        [DisplayName("Ngày trả")]
        public Nullable<System.DateTime> NgayTra { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual ThongTinKhachHang ThongTinKhachHang { get; set; }
        public virtual LoaiXe LoaiXe { get; set; }
    }
}
