//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OToChoThue.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ThongTinKhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinKhachHang()
        {
            this.DonThueXes = new HashSet<DonThueXe>();
        }
        [DisplayName("ID của khách hàng")]
        public string KhachHangID { get; set; }
        [DisplayName("Họ và tên")]
        public string HoTen { get; set; }
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Số điện thoại")]
        public string SoDienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonThueXe> DonThueXes { get; set; }
    }
}
